### ISSUE TITLE
Merge js-libp2p-connection into libp2p

### ISSUE THREAD

**Issue by achingbrain** [libp2p/js-libp2p-connection#9]
From what I can see, the only consumer of this module is libp2p so maybe the code can just be folded in there.

**Comment by TinyTb** [comment]
<img width="1207" alt="Screen Shot 2022-11-15 at 8 54 47 AM" src="https://user-images.githubusercontent.com/5957298/201979522-0a1be84d-9ab1-4cb6-95df-f3383f8b0f20.png">
Confirmed no other dependents 👍
